#!/bin/zsh
# Daily Action Brief for the rep channels: composes each rep's morning execution brief
# (replies first, calls with scripts, approvals, voice notes, autopilot line) from the
# Lemlist task queues + relay reply logs, in the format pinned by
# automation/config/action_brief_format.md. Gated by action_brief_gate.py (weekday,
# rep-local 07:00-08:30, once per day). Own live flag in config/action_brief.json;
# live=false renders to the log only. Never DMs Dallas (single-morning-brief rule);
# the daily rundown reads this job's log. FIXTURE=1 composes from
# config/action_brief_fixture.json instead of the live API (render test, never posts).
set -uo pipefail
cd "/Users/dallasandrews/Claude/Projects/Intradiem GTM Engineer"

if [[ "${FIXTURE:-0}" == "1" ]]; then
  DUE='["jack","nathan"]'
  FIXTURE_LINE="FIXTURE MODE: compose from automation/config/action_brief_fixture.json instead of calling the Lemlist API. Treat its tasks/replies as the live queues. NEVER post to Slack in fixture mode regardless of any live flag; write renders to the log only."
else
  DUE=$(python3 automation/action_brief_gate.py) || exit 0
  FIXTURE_LINE=""
fi

if [[ "$DUE" == "[]" ]]; then
  echo "$(date '+%Y-%m-%d %H:%M') gate: nobody due" >> "automation/logs/_run_action_brief.out"
  exit 0
fi

"/Users/dallasandrews/Claude/Projects/Intradiem GTM Engineer/automation/lib/claude_net.sh" --model claude-sonnet-5 -p "$(cat <<PROMPT
Unattended scheduled run: Daily Action Brief composer for rep channels. Nobody is watching live.

Reps due this run: $DUE
$FIXTURE_LINE

Config: automation/config/action_brief.json (reps, brief definitions, campaigns per brief, live flag, state.last_posted). Routing: automation/config/lemlist_channels.json (channels + route names; READ ONLY, never edit it). Auth: automation/config/lemlist.env has LEMLIST_API_KEY. Format contract: automation/config/action_brief_format.md, follow it exactly.

Do exactly this, for each due rep, for each of that rep's briefs:
1. Fetch open tasks: curl -s -u ":\$LEMLIST_API_KEY" "https://api.lemlist.com/api/tasks?filters=%5B%5D" (filters param REQUIRED, %5B%5D = empty array; done tasks are excluded by the API). Keep only tasks whose campaignId belongs to this brief. HELD LEADS: if this brief's config carries a "held_leads" array, EXCLUDE those leads' tasks from every approval/task list in the brief and render exactly one line for each at the bottom of the brief's task section: "Held for Dallas: <name> (<company>) - do not action in Lemlist." Never list a held lead as an approval, a call, or any actionable item, regardless of what the task queue says.
2. Replies: read today's and yesterday's automation/logs/lemlist-relay-*.md for replied leads in this brief's campaigns that still need action, and automation/logs/brief-thread-ingest-*.md for DONE/SKIP/HOLD state (a lead marked DONE or HOLD is listed as such, never re-assigned as a fresh task). Replies always lead the brief. THE RELAY OWNS REPLY DRAFTS: if the relay log carries a draft for a reply, reference it ("draft is in the relay alert above, ready to edit"), never compose a competing draft; draft fresh only when no relay draft exists. A fresh draft does NOT go in the main message body: it posts as a THREADED message under the brief (see step 5), and the main message says "Your reply is drafted, first message in this thread. Send it from your inbox (edit it first if you want), then reply <Name> DONE here. Want a different angle? Say it here and I'll redraft." (per the format spec's fresh-reply wording; plain action words, never "approve it") NEVER write that a draft is threaded, attached, or queued unless this run actually posts it; that false claim shipped once and is a named defect.
3. Render copy per the format spec, PER ITEM TYPE (the spec's PER-TYPE LAYOUTS section is the contract): email drafts render as real emails inside the code block (greeting on its own line, blank line between paragraphs, sign-off on its own line, Subject: line only for new sends); call scripts render as labeled segments (bold label + own code block: Opener / If they engage / The ask / If they're busy / If they brush you off / If pushback - "<objection>" / No answer - voicemail), NEVER one merged paragraph and never an objection handle folded into the opener; openers follow the four-beat skeleton in motions/shared/Cold_Call_Playbook_Aug2.md (name, who you are, the reason for the call from the lead's real hook, then the 30-second contract with the prospect in control) and NEVER open with an availability yes/no ("did I catch you at a bad time / an OK moment / with 30 seconds"); the If-they-engage segment ends on a check question; busy and brush-off branches render on dial tasks from that playbook's shapes with the motion slot filled from the lead's variables; the brush-off block always ends on its release line with nothing after it; BRANCH CAP: at most seven labeled blocks and at most two pushback blocks per call, chosen by relevance (a relevance rule, never a wording trim); OPENER FACT CHECK on live (non-fixture) composition: every number, name, and fact in a composed opener must trace to the lead's stored variables or this brief's playbook_sources, anything untraceable means recompose without it or fall back to "copy is loaded in the Lemlist task", and write one OPENER-CHECK line per composed dial script to the log naming the lead, the facts used, and the source variable of each; voicemail-only, voice notes, DMs stay one block each. Objection-handle blocks are sourced from this brief's playbook_sources files listed in action_brief.json (read them from the repo root) and rendered in spoken form (claims, facts, mechanism unchanged, never strengthened, no new numbers); include only relevant ones, omit when none match, never write a new handle. Resolve {{variables}} from the lead's custom variables (curl -s -u ":\$LEMLIST_API_KEY" "https://api.lemlist.com/api/leads/<leadId or email>"). In fixture mode, tasks carry a "script" object whose keys map 1:1 to the labeled segments; render each key as its own block. If a variable will not resolve, point to the Lemlist task instead; NEVER invent copy, never guess a script.
4. Autopilot sends, full copy (format spec AUTOPILOT SENDS section is the contract): the main message keeps the one-line counts summary; every automated EMAIL firing today ALSO renders in full as a threaded message under the brief (always threaded, never in the main message; last in thread order after reply drafts and overflow sections). Source the copy from the campaign's sequence steps via the API (curl -s -u ":\$LEMLIST_API_KEY" "https://api.lemlist.com/api/campaigns/<campaignId>/sequences", adapt if the endpoint shape differs) plus each lead's variables. Group by step: bold header with lane/step/count, recipient names + companies, then the email per the Email layout with its Subject: line. Distinct per-lead copy renders every lead's email in full; a shared template renders ONCE with {{variables}} left visible above the recipient list. If today's exact recipient set is not derivable from the API, render the in-flight step's copy with the campaign-level count and "recipient schedule is in Lemlist"; if the step copy itself will not resolve, name the step and point to Lemlist. NEVER fabricate a recipient list, never invent or reconstruct send copy. Visits/likes/follows stay counts only. In fixture mode the fixture's autopilot object carries "summary" plus a "sends" array; render sends exactly as staged. The summary line's pointer ("Full copy of today's emails is in this thread.") appears only when the sends thread actually posts (or, dry run, actually renders).
5. Silence on empty, per brief: zero replies and zero open tasks means that brief is not composed and nothing posts for it; write one skip line to the log. Overflow per the format spec: scripts NEVER drop; past ~4000 chars, thread the later sections under the main message instead of trimming, and split Nate's brief per lane if threading is not enough. The "Yesterday" tally comes only from Lemlist completions plus the thread-ingest logs; omit it when there is no data.
6. Check "live" in action_brief.json:
   - live=false: post NOTHING anywhere. Write every composed brief verbatim into automation/logs/action-brief-<today>.md under a "DRY RUN" header, one section per brief, including which channel it WOULD have gone to, and render every would-be threaded message right after its parent brief under a "↳ THREAD" marker line so the render shows the exact live split.
   - live=true: compose the main message AND all its threaded messages first, then post the main brief as one Slack message to the channel id that this rep's route name maps to in lemlist_channels.json "channels" (channels only, never a DM), capture the posted message's ts from the send result, then post each threaded message with thread_ts set to that ts, in order: one "✉️ Draft reply for <Name> (<Company>):" message per fresh reply draft, then any overflow sections. If a threaded post fails after one retry, log the draft under a FAILED-THREAD header. Then write main message plus threads to the log.
7. After a rep's briefs are handled (posted, or dry-run rendered), set state.last_posted["<rep>"] to today's date in that rep's timezone inside automation/config/action_brief.json, changing nothing else in the file. In fixture mode, skip this step entirely.

Draft-reply guardrails (these are the three failure modes prior runs actually produced, treat them as hard): (a) BANNED PHRASES, never in any draft: "comparing notes" / "compare notes", the leverage/lever family, seamless, robust, transform(ation), innovative, comprehensive, empower, cutting-edge, best-in-class, synergy, "circle back", "touch base", "reach out", "happy to", "I'd love to". (b) NEVER imply other customers, carriers, plans, or conversations that are not Repository-verified. If a prospect asks "who else are you working with", the draft acknowledges the question and pivots to their situation without naming or implying anyone; it never claims other engagements exist. Drafts describe patterns and mechanisms, not a client roster. (c) SPOKEN VOICE AND WARMTH, per the format spec's SPOKEN VOICE section: every draft and script must read as something the rep would say out loud in a real conversation, no writerly phrasing, no aphorisms, no stacked clauses; and a draft may decline to answer something but never sounds like a refusal ("I'm not going to give you a list" shipped once and is a named defect; the shape is "fair to ask, I would too" plus an honest reason, then the pivot). Match the register of the two reference drafts in the format spec.

Hard rules: ALWAYS compose fresh on every run; never skip or shortcut composition because today's log already holds a render or the fixture/queues look unchanged (a prior run did this with a false "content identical" claim while the spec had changed; it is a named defect). The format spec and this prompt are inputs to every composition, so an unchanged fixture does NOT mean an unchanged render. Never DM anyone, Dallas included (his daily rundown reads the log). Never post to a channel not in lemlist_channels.json. Never start, pause, or edit any campaign, sequence, lead, or task. Never invent an Intradiem number; drafts carry no stats. No em dashes in anything rep-facing. Do not modify any file except automation/logs/* and the state.last_posted object in automation/config/action_brief.json. Never touch lemlist_channels.json or the relay's seen_activity_ids.
PROMPT
)" --dangerously-skip-permissions >> "automation/logs/_run_action_brief.out" 2>&1
